-- =============================================================================
-- SERVITACO - Datos de propietario, código de línea y contrato de servicio
-- Rama: feature-mant_vehiculo
-- Campos existentes en el sistema legado (Excel) y nunca migrados a SQL Server.
-- =============================================================================

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE ServitacoDB;
GO

ALTER TABLE flota.Vehiculo ADD
    rut_propietario         VARCHAR(12)     NULL,
    nombre_propietario      VARCHAR(150)    NULL,
    direccion_propietario   VARCHAR(300)    NULL,
    telefono_propietario    VARCHAR(20)     NULL,
    email_propietario       VARCHAR(150)    NULL,
    codigo_linea             VARCHAR(20)     NULL,
    contrato_servicio        VARCHAR(255)    NULL;  -- texto libre: fecha, "SI" o ruta a archivo, según el registro original
GO

-- =============================================================================
-- Backfill generado desde SERVITACO_V11_2026.xlsm (hoja BASE_AUTOS)
-- 136 vehículos. Dos anomalías de datos detectadas y preservadas tal cual
-- (no se inventan valores correctos):
--   - LZVK-66: rut_propietario mal formado en el origen ('130042414', sin guión/DV)
--   - JWKL-63: direccion_propietario contiene un RUT en vez de una dirección
-- =============================================================================

UPDATE flota.Vehiculo SET rut_propietario = '15123366-K', nombre_propietario = 'CRISTIAN ARANCIBIA LABORDE', direccion_propietario = 'ACA', telefono_propietario = '987654321', email_propietario = 'ACA@GMAIL.COM', codigo_linea = '900', contrato_servicio = NULL WHERE patente = 'AAAA-11';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'CALLE ESPAÑA N° 467', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '631', contrato_servicio = NULL WHERE patente = 'BXSH-97';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'CALLE ESPAÑA N° 467', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '643', contrato_servicio = NULL WHERE patente = 'BXXZ-58';
UPDATE flota.Vehiculo SET rut_propietario = '13200849-3', nombre_propietario = 'SERGIO ALEJANDRO SALINAS ROMERO', direccion_propietario = 'POBLACION VILLA LA RAMADA JUAN GODOY  N° 130', telefono_propietario = '976118939', email_propietario = NULL, codigo_linea = '651', contrato_servicio = NULL WHERE patente = 'CXWH-76';
UPDATE flota.Vehiculo SET rut_propietario = '11530656-9', nombre_propietario = 'MANUEL FRANCISCO BECERRA IBARRA', direccion_propietario = 'VILLA SAN JUAN BLOCK 2 DPTO 36 SAN FERNANDO', telefono_propietario = '986563399', email_propietario = NULL, codigo_linea = '648', contrato_servicio = NULL WHERE patente = 'PVSD-58';
UPDATE flota.Vehiculo SET rut_propietario = '6744579-1', nombre_propietario = 'LUIS ARTURO MARTINEZ DIAZ', direccion_propietario = 'CURALI N° 330 SAN FERNANDO', telefono_propietario = '975715183', email_propietario = NULL, codigo_linea = '659', contrato_servicio = NULL WHERE patente = 'DHYT-76';
UPDATE flota.Vehiculo SET rut_propietario = '11760555-8', nombre_propietario = 'MARIA NUÑEZ CARRIZO', direccion_propietario = 'VILLA ESTER 3 PASAJE NUEVO HORIZONTE 1023  SAN FERNANDO', telefono_propietario = '981240808', email_propietario = NULL, codigo_linea = '708', contrato_servicio = NULL WHERE patente = 'FDVB-57';
UPDATE flota.Vehiculo SET rut_propietario = '12413397-1', nombre_propietario = 'HECTOR ITALO SALAZAR SOTO', direccion_propietario = 'CALLE UNO N° 427 SAN FERNANDO', telefono_propietario = '962329580', email_propietario = NULL, codigo_linea = '668', contrato_servicio = NULL WHERE patente = 'PVSD-68';
UPDATE flota.Vehiculo SET rut_propietario = '14260593-7', nombre_propietario = 'MANUEL JESUS VIDELA CHAVEZ', direccion_propietario = 'ROMA LO CARREÑO S/N', telefono_propietario = '947480094', email_propietario = NULL, codigo_linea = '735', contrato_servicio = NULL WHERE patente = 'FDVZ-60';
UPDATE flota.Vehiculo SET rut_propietario = '10916547-6', nombre_propietario = 'HECTOR WENCESLAO  FIGUEROA TAPIA', direccion_propietario = 'POBLACION LOS HUERTOS N° 64 SAN FERNANDO', telefono_propietario = '944893375', email_propietario = NULL, codigo_linea = '671', contrato_servicio = NULL WHERE patente = 'FDVZ-84';
UPDATE flota.Vehiculo SET rut_propietario = '11433470-7', nombre_propietario = 'MAURICIO CASTILLO DÍAZ', direccion_propietario = 'VILLA PAUL HARRIS 2 PJE PEDRO GINESTAR  27 SAN FERNANDO', telefono_propietario = '961630714', email_propietario = NULL, codigo_linea = '635', contrato_servicio = NULL WHERE patente = 'FDWJ-84';
UPDATE flota.Vehiculo SET rut_propietario = '15117507-4', nombre_propietario = 'RICHARD ANDRES CARREÑO SILVA', direccion_propietario = 'NEGRETE N° 433 SAN FERNANDO', telefono_propietario = '963006368', email_propietario = NULL, codigo_linea = '656', contrato_servicio = NULL WHERE patente = 'FDWK-69';
UPDATE flota.Vehiculo SET rut_propietario = '13304265-2', nombre_propietario = 'ELSA DEL CARMEN ROMERO SOLIS', direccion_propietario = 'ROMERAL ADENTRO S/N CHIMBARONGO', telefono_propietario = '930382399', email_propietario = NULL, codigo_linea = '704', contrato_servicio = NULL WHERE patente = 'FDWX-91';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'POBL.  PABLO NERUDA PJE 9 CASA 94 SAN FERNANDO', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '722', contrato_servicio = NULL WHERE patente = 'FDXV-71';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'PARCELA 4 MANZANA D MIRAVALLES SAN FERNANDO', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '680', contrato_servicio = NULL WHERE patente = 'FDXV-86';
UPDATE flota.Vehiculo SET rut_propietario = '7146476-8', nombre_propietario = 'JAVIER BENITO CORREA CANTILLANA', direccion_propietario = 'CALLE ARAUCO N° 020 SAN FERNANDO', telefono_propietario = '974883709', email_propietario = NULL, codigo_linea = '707', contrato_servicio = NULL WHERE patente = 'FJXZ-11';
UPDATE flota.Vehiculo SET rut_propietario = '8259372-1', nombre_propietario = 'LUIS MANUEL PALMA MOYA', direccion_propietario = 'MANUEL RODRIGUEZ PONIENTE N°0761 VILLA LAS TINAJAS SAN FERNANDO', telefono_propietario = '920217634', email_propietario = NULL, codigo_linea = '612', contrato_servicio = '11/8/21' WHERE patente = 'FKCR-79';
UPDATE flota.Vehiculo SET rut_propietario = '17059232-8', nombre_propietario = 'SEBASTIAN ADOLFO ROMAN RAMIREZ', direccion_propietario = 'VILLA EDUARDO BARRIOS 3 PASAJE ROSITA RENORD 0283 SAN FERNANDO', telefono_propietario = '968328258', email_propietario = NULL, codigo_linea = '710', contrato_servicio = NULL WHERE patente = 'FLZP-55';
UPDATE flota.Vehiculo SET rut_propietario = '15117911-8', nombre_propietario = 'LUIS ARMANDO VERGARA MORENO', direccion_propietario = 'PASAJE LOS ESTRIBEROS N° 1749 VILLA EL RODEO SAN FERNANDO', telefono_propietario = '947709975', email_propietario = NULL, codigo_linea = '681', contrato_servicio = NULL WHERE patente = 'FXLR-13';
UPDATE flota.Vehiculo SET rut_propietario = '15914358-9', nombre_propietario = 'CYNTHIA LISSETTE TAPIA HERRERA', direccion_propietario = 'CIRCUNVALACION N° 212 NINCULAUTA SAN FERNANDO', telefono_propietario = '941760094', email_propietario = NULL, codigo_linea = '685', contrato_servicio = NULL WHERE patente = 'FXVK-87';
UPDATE flota.Vehiculo SET rut_propietario = '8752048-6', nombre_propietario = 'NANCY ANGELICA RIVERA ELIZONDO', direccion_propietario = 'LOS HUERTOS N° 41 SAN FERNANDO', telefono_propietario = '983302213', email_propietario = NULL, codigo_linea = '684', contrato_servicio = NULL WHERE patente = 'GBYP-67';
UPDATE flota.Vehiculo SET rut_propietario = '10726874-K', nombre_propietario = 'JAVIER ERNESTO ARENAS MARAMBIO', direccion_propietario = 'LOS AROMOS N° 1900 SAN FERNANDO', telefono_propietario = '962613506', email_propietario = NULL, codigo_linea = '657', contrato_servicio = NULL WHERE patente = 'GBYP-78';
UPDATE flota.Vehiculo SET rut_propietario = '15698448-5', nombre_propietario = 'CRISTIAN RAUL GUTIERREZ NUÑEZ', direccion_propietario = 'VILLA SAN MARCO CALLE SAN PABLO N° 0142', telefono_propietario = '982584052', email_propietario = NULL, codigo_linea = '723', contrato_servicio = NULL WHERE patente = 'GBZF-21';
UPDATE flota.Vehiculo SET rut_propietario = '14261886-9', nombre_propietario = 'PABLO ANDRES BENAVENTE ASTORGA', direccion_propietario = 'CALLE EL QUILO N° 148 SAN FERNANDO', telefono_propietario = '995225802', email_propietario = NULL, codigo_linea = '698', contrato_servicio = NULL WHERE patente = 'GBZV-36';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'POBLACION PABLO NERUDA PASAJE 9 CASA 94  SAN FERNANDO', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '701', contrato_servicio = NULL WHERE patente = 'GPXK-41';
UPDATE flota.Vehiculo SET rut_propietario = '11761569-3', nombre_propietario = 'MARIA PILAR HERRERA ZUÑIGA', direccion_propietario = 'CALLE EL ROBLE N° 264', telefono_propietario = '993174851', email_propietario = NULL, codigo_linea = '695', contrato_servicio = NULL WHERE patente = 'GPYW-59';
UPDATE flota.Vehiculo SET rut_propietario = '14260593-7', nombre_propietario = 'MANUEL VIDELA CHAVEZ', direccion_propietario = 'ROMA LO CARREÑO S/N', telefono_propietario = '947480094', email_propietario = NULL, codigo_linea = '736', contrato_servicio = NULL WHERE patente = 'GPYW-93';
UPDATE flota.Vehiculo SET rut_propietario = '5246025-5', nombre_propietario = 'SERGIO DEL CARMEN SALAZAR RETAMALES', direccion_propietario = 'MONTE NEGRO 07 CHIMBARONGO', telefono_propietario = '996281232', email_propietario = NULL, codigo_linea = '611', contrato_servicio = '6/9/21' WHERE patente = 'GYCY-50';
UPDATE flota.Vehiculo SET rut_propietario = '13569694-3', nombre_propietario = 'CRISTIAN ANDRES REBOLLEDO BUSTOS', direccion_propietario = 'POBLACION BELLA VISTA BLOCK 8DPTO 203', telefono_propietario = '989705475', email_propietario = NULL, codigo_linea = '616', contrato_servicio = NULL WHERE patente = 'HBLL-48';
UPDATE flota.Vehiculo SET rut_propietario = '15915952-3', nombre_propietario = 'JOSE RODRIGO CANTILLANA BURGOS', direccion_propietario = 'NINCUNLAUTA N° 216 SAN FERNANDO', telefono_propietario = '992052298', email_propietario = NULL, codigo_linea = '666', contrato_servicio = NULL WHERE patente = 'HDJY-97';
UPDATE flota.Vehiculo SET rut_propietario = '11743655-1', nombre_propietario = 'ANGEL ALVEAR CABEZAS', direccion_propietario = 'AV. JULIO FERNANDEZ S/N AGUA BUENA SAN FERNANDO', telefono_propietario = '957694364', email_propietario = NULL, codigo_linea = '729', contrato_servicio = NULL WHERE patente = 'HGGK-75';
UPDATE flota.Vehiculo SET rut_propietario = '13347360-2', nombre_propietario = 'ELGA DEL CARMEN SILVA CORTES', direccion_propietario = 'PASAJE LOS MANZANOS N° 015 SAN FERNANDO', telefono_propietario = '990561062', email_propietario = NULL, codigo_linea = '700', contrato_servicio = NULL WHERE patente = 'HGGW-14';
UPDATE flota.Vehiculo SET rut_propietario = '13569906-3', nombre_propietario = 'LUIS HUMERTO MENESES RODRIGUEZ', direccion_propietario = 'PSJE CLAUDIO FUENTES BLOCK 22 DPTO 104', telefono_propietario = '958548377', email_propietario = NULL, codigo_linea = '639', contrato_servicio = NULL WHERE patente = 'PVSF-16';
UPDATE flota.Vehiculo SET rut_propietario = '15649660-K', nombre_propietario = 'CECILIA ANDREA MUÑOZ ESPINA', direccion_propietario = 'RENATO GAONA 570 VILLA DOÑA ESTER 4 SAN FERNANDO', telefono_propietario = '922393106', email_propietario = NULL, codigo_linea = '690', contrato_servicio = NULL WHERE patente = 'HGHJ-91';
UPDATE flota.Vehiculo SET rut_propietario = '11279202-3', nombre_propietario = 'MARCELA DEL ROSARIO OSORIO ASTUDILLO', direccion_propietario = 'GABRIELA MISTRAL TERNURA N° 1050 SAN FERNANDO', telefono_propietario = '975585200', email_propietario = NULL, codigo_linea = '696', contrato_servicio = NULL WHERE patente = 'HGHT-93';
UPDATE flota.Vehiculo SET rut_propietario = '6178392-K', nombre_propietario = 'MARIA INES HIDALGO VILLALOBOS', direccion_propietario = 'POLONIA PARCELA 24 B SAN FERNANDO', telefono_propietario = '973198408', email_propietario = NULL, codigo_linea = '622', contrato_servicio = NULL WHERE patente = 'HGHT-94';
UPDATE flota.Vehiculo SET rut_propietario = '7354610-9', nombre_propietario = 'ANGEL GALARCE GALARCE', direccion_propietario = 'RINCONADA DE MANANTIALES PLACILLA', telefono_propietario = '964136287', email_propietario = NULL, codigo_linea = '724', contrato_servicio = NULL WHERE patente = 'HGHV-19';
UPDATE flota.Vehiculo SET rut_propietario = '11530199-3', nombre_propietario = 'MARIO ZUÑIGA G', direccion_propietario = 'GABRIELA MISTRAL PETRONILA ALCAYAGA N° 1025', telefono_propietario = '985378365', email_propietario = 'mzuñiga@gmail.com', codigo_linea = '604', contrato_servicio = NULL WHERE patente = 'HJVG-42';
UPDATE flota.Vehiculo SET rut_propietario = '8045345-0', nombre_propietario = 'NELSON ORLANDO BOZO BECERRA', direccion_propietario = 'CHILLAN 525 SA FERNANDO', telefono_propietario = '999579931', email_propietario = NULL, codigo_linea = '738', contrato_servicio = 'SI' WHERE patente = 'JWHC-56';
UPDATE flota.Vehiculo SET rut_propietario = '8159142-3', nombre_propietario = 'PATRICIO SEGUNDO IBARRA ARAYA', direccion_propietario = 'CENTINELA SUR SAN FERNANDO', telefono_propietario = '958395252', email_propietario = NULL, codigo_linea = '694', contrato_servicio = NULL WHERE patente = 'HWYJ-33';
UPDATE flota.Vehiculo SET rut_propietario = '7354610-9', nombre_propietario = 'ANGEL GALARCE GALARCE', direccion_propietario = 'RINCONADA DE MANANTIALES PLACILLA', telefono_propietario = '964136287', email_propietario = NULL, codigo_linea = '630', contrato_servicio = NULL WHERE patente = 'HWYJ-65';
UPDATE flota.Vehiculo SET rut_propietario = '15916725-9', nombre_propietario = 'DANAES IBARRA ORELLANA', direccion_propietario = 'PJE LAUTARO YANKAS 0 SAN FERNANDO', telefono_propietario = '958861006', email_propietario = NULL, codigo_linea = '615', contrato_servicio = NULL WHERE patente = 'HWYJ-95';
UPDATE flota.Vehiculo SET rut_propietario = '11743655-1', nombre_propietario = 'ANGEL RAMON ALVEAR CABEZAS', direccion_propietario = 'AV. JULIO FERNANDEZ S/N° AGUA BUENA SAN FERNANDO', telefono_propietario = '995769364', email_propietario = NULL, codigo_linea = '716', contrato_servicio = NULL WHERE patente = 'HWZG-63';
UPDATE flota.Vehiculo SET rut_propietario = '10858763-6', nombre_propietario = 'JULIA DE LAS MERCEDES VIDELA CHAVEZ', direccion_propietario = 'ROMA LO CARREÑO S/N° SAN FERNANDO', telefono_propietario = '947480094', email_propietario = NULL, codigo_linea = '608', contrato_servicio = '10/4/23' WHERE patente = 'JVDZ-30';
UPDATE flota.Vehiculo SET rut_propietario = '7957636-0', nombre_propietario = 'TERESA DEL TRANSITO MOENA QUEZADA', direccion_propietario = 'SANTA AMELIA N°1 POBL.SANTA ELENA  SAN FERNANDO', telefono_propietario = '722915121', email_propietario = NULL, codigo_linea = '645', contrato_servicio = NULL WHERE patente = 'JWHB-70';
UPDATE flota.Vehiculo SET rut_propietario = '5467133-4', nombre_propietario = 'GILLERMO ALFONSO GUAJARDO GONZALEZ', direccion_propietario = 'LOS PALACIOS 1312 BLOCK 5 DPTO 13 SAN FERNANDO', telefono_propietario = '922936683', email_propietario = NULL, codigo_linea = '658', contrato_servicio = NULL WHERE patente = 'JWHB-83';
UPDATE flota.Vehiculo SET rut_propietario = '13346398-4', nombre_propietario = 'ANGEL CUSTODIO BARRERA CABRERA', direccion_propietario = 'VILLA RUCATALCA PASAJE LOS CIRUELOS 0202 SAN FERNANDO', telefono_propietario = '988652582', email_propietario = NULL, codigo_linea = '683', contrato_servicio = NULL WHERE patente = 'JWHC-17';
UPDATE flota.Vehiculo SET rut_propietario = '18989824-K', nombre_propietario = 'CAMILO DEL CARMEN LOPEZ MENESES', direccion_propietario = 'AMBROSIO O´HHIGINS 0144', telefono_propietario = '934183947', email_propietario = NULL, codigo_linea = '713', contrato_servicio = NULL WHERE patente = 'JWJF-56';
UPDATE flota.Vehiculo SET rut_propietario = '5030538-4', nombre_propietario = 'HOMERO GUILLERMO MUÑOZ VILLABLANCA', direccion_propietario = 'LA MEDIA LUNA 606 SAN FERNANDO', telefono_propietario = '722915805', email_propietario = NULL, codigo_linea = '650', contrato_servicio = NULL WHERE patente = 'JWJY-11';
UPDATE flota.Vehiculo SET rut_propietario = '14260593-7', nombre_propietario = 'MANUEL VIDELA CHAVEZ', direccion_propietario = 'LO CARREÑO S/N', telefono_propietario = '947488094', email_propietario = NULL, codigo_linea = '665', contrato_servicio = '21/12/2025' WHERE patente = 'JWJY-22';
UPDATE flota.Vehiculo SET rut_propietario = '14261222-4', nombre_propietario = 'PAOLA DEL CARMEN FARIAS ROMERO', direccion_propietario = 'NEGRETE N° 1270 SAN FERNANDO', telefono_propietario = '722711936', email_propietario = NULL, codigo_linea = '730', contrato_servicio = NULL WHERE patente = 'JWKL-38';
UPDATE flota.Vehiculo SET rut_propietario = '17746912-2', nombre_propietario = 'CAMILA RIVERA BECERRA', direccion_propietario = '17746912-2', telefono_propietario = '983197274', email_propietario = NULL, codigo_linea = '693', contrato_servicio = NULL WHERE patente = 'JWKL-63';
UPDATE flota.Vehiculo SET rut_propietario = '10737580-5', nombre_propietario = 'RAMON ORELLANA H', direccion_propietario = 'POLONIA S/N', telefono_propietario = '973198408', email_propietario = 'ramoorellana@gmail.com', codigo_linea = '605', contrato_servicio = 'NA3' WHERE patente = 'JWKL-71';
UPDATE flota.Vehiculo SET rut_propietario = '10643083-7', nombre_propietario = 'MARIA VICTORIA ORELLANA HIDALGO', direccion_propietario = 'SANTA ISABEL DE POLONIA', telefono_propietario = '973198408', email_propietario = NULL, codigo_linea = '653', contrato_servicio = NULL WHERE patente = 'JWKL-73';
UPDATE flota.Vehiculo SET rut_propietario = '10914820-2', nombre_propietario = 'WENCESLAO DEL CARMEN GONZALEZ VARA', direccion_propietario = 'VILLA ESTER 2 CIRCUNVALACION  743 SAN FERNANDO', telefono_propietario = '936126858', email_propietario = NULL, codigo_linea = '641', contrato_servicio = NULL WHERE patente = 'RPFY-69';
UPDATE flota.Vehiculo SET rut_propietario = '5246025-5', nombre_propietario = 'SERGIO DEL CARMEN SALAZAR RETAMALES', direccion_propietario = 'MONTENEGRO 07 TINGUIRIRICA CHIMBARONGO', telefono_propietario = '996281232', email_propietario = NULL, codigo_linea = '711', contrato_servicio = NULL WHERE patente = 'KCRG-93';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'CALLE ESPAÑA N° 467 SAN FERNANDO', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '661', contrato_servicio = NULL WHERE patente = 'KCXB-59';
UPDATE flota.Vehiculo SET rut_propietario = '9271681-3', nombre_propietario = 'AMBROSIO DEL CARMEN FUENTES CORNEJO', direccion_propietario = 'POBL. 18 DE SEPTIEMBRE MANZANA 12 CASA 2', telefono_propietario = '995115810', email_propietario = NULL, codigo_linea = '660', contrato_servicio = NULL WHERE patente = 'KCXB-68';
UPDATE flota.Vehiculo SET rut_propietario = '14352221-0', nombre_propietario = 'ALBARDO DE JESUS PAVEZ CLAVIJO', direccion_propietario = 'POBL. EDUARDO BARRIO PJE EDUARDO ANGUITA N° 1761', telefono_propietario = '977234892', email_propietario = NULL, codigo_linea = '644', contrato_servicio = NULL WHERE patente = 'KCXB-75';
UPDATE flota.Vehiculo SET rut_propietario = '7550372-5', nombre_propietario = 'GLORIA ANGELICA RAMIREZ VIDELA', direccion_propietario = 'NEGRETE 170 SAN FERNANDO', telefono_propietario = '989737882', email_propietario = NULL, codigo_linea = '625', contrato_servicio = NULL WHERE patente = 'KCXB-76';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'NEGRETE N° 1270 SAN FERNANDO', telefono_propietario = '972940365', email_propietario = NULL, codigo_linea = '609', contrato_servicio = '5/11/21' WHERE patente = 'KCXP-33';
UPDATE flota.Vehiculo SET rut_propietario = '6935231-6', nombre_propietario = 'JUAN VASQUEZ DAZA', direccion_propietario = 'VILLA SUR PSJE CENTRAL N° 1491 SAN FERNANDO', telefono_propietario = '993790529', email_propietario = 'juanvasquez@gmail.com', codigo_linea = '603', contrato_servicio = NULL WHERE patente = 'KCXP-40';
UPDATE flota.Vehiculo SET rut_propietario = '15915893-4', nombre_propietario = 'GABRIEL AMBROSIO FUENTES VIEDMA', direccion_propietario = 'POBL. 18 DE SEPTIEMBRE PJE CAMILO HENRIQUEZ 1480 SAN FERNANDO', telefono_propietario = '972940365', email_propietario = NULL, codigo_linea = '733', contrato_servicio = NULL WHERE patente = 'KCXP-53';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'NEGRETE N°  1270 SAN FERNADO', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '687', contrato_servicio = NULL WHERE patente = 'KCYK-57';
UPDATE flota.Vehiculo SET rut_propietario = '17058993-9', nombre_propietario = 'JAVIER ALEJANDRO OJEDA BASTIAS', direccion_propietario = 'VILLA DOLIT N°42 VILLA ESPAÑA SAN FERNANDO', telefono_propietario = '977258988', email_propietario = NULL, codigo_linea = '627', contrato_servicio = NULL WHERE patente = 'KCYK-78';
UPDATE flota.Vehiculo SET rut_propietario = '12413613-K', nombre_propietario = 'SIMON PEDRO IGLESIAS SANCHEZ', direccion_propietario = 'LA MARINANA ROMA SAN FERNANDO', telefono_propietario = '968273534', email_propietario = NULL, codigo_linea = '638', contrato_servicio = NULL WHERE patente = 'KCYR-37';
UPDATE flota.Vehiculo SET rut_propietario = '8892584-K', nombre_propietario = 'ELSA MARINA CATALAN CORNEJO', direccion_propietario = 'POBLSCION GABRIELA N° 17 SAN FERNANDO', telefono_propietario = '989233557', email_propietario = NULL, codigo_linea = '679', contrato_servicio = NULL WHERE patente = 'KCYR-40';
UPDATE flota.Vehiculo SET rut_propietario = '6940525-8', nombre_propietario = 'JUAN ANTONIO CORTEZ ORELLANA', direccion_propietario = 'VILLA SUR 1454 SAN FERNANDO', telefono_propietario = '989938218', email_propietario = NULL, codigo_linea = '614', contrato_servicio = '16-02-2022' WHERE patente = 'KCYR-46';
UPDATE flota.Vehiculo SET rut_propietario = '11743655-1', nombre_propietario = 'ANGEL RAMON ALVEAR CABEZAS', direccion_propietario = 'AV. JULIO FERNANDEZ  SAN FERNANDO', telefono_propietario = '957694364', email_propietario = NULL, codigo_linea = '712', contrato_servicio = NULL WHERE patente = 'KCYR-50';
UPDATE flota.Vehiculo SET rut_propietario = '13779705-4', nombre_propietario = 'FELIPE ALEJANDRO VALDERRAMA GONZALEZ', direccion_propietario = 'AV. CIRCUNVALACION PONIENTE N° 648 SAN FERNANDO', telefono_propietario = '962803880', email_propietario = NULL, codigo_linea = '715', contrato_servicio = NULL WHERE patente = 'KCYY-63';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'POBL. PABLO NERUDA PJE. 9 CASA 94', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '720', contrato_servicio = NULL WHERE patente = 'KCYY-84';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'NEGRETE N° 1270 SAN FERNANDO', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '721', contrato_servicio = NULL WHERE patente = 'KCYY-85';
UPDATE flota.Vehiculo SET rut_propietario = '11952903-4', nombre_propietario = 'PATRICIO EDUARDO FARIAS ROMERO', direccion_propietario = 'NEGRETE N° 1270 SAN FERNANDO', telefono_propietario = '995667159', email_propietario = NULL, codigo_linea = '706', contrato_servicio = NULL WHERE patente = 'KCZR-57';
UPDATE flota.Vehiculo SET rut_propietario = '13780194-9', nombre_propietario = 'KAREN GENEPES CACERES GALVEZ', direccion_propietario = 'EL ENCINO 527 VILLA GEORGINA 2 SAN FERNANDO', telefono_propietario = '995840868', email_propietario = NULL, codigo_linea = '702', contrato_servicio = NULL WHERE patente = 'KYGL-64';
UPDATE flota.Vehiculo SET rut_propietario = '7532446-4', nombre_propietario = 'ALFONSO LINCOYAN SALDAÑA FLORES', direccion_propietario = 'VILLA CENTINELA LUIS AMESTI 1478 SAN FERNANDO', telefono_propietario = '995489971', email_propietario = NULL, codigo_linea = '726', contrato_servicio = NULL WHERE patente = 'KYGL-91';
UPDATE flota.Vehiculo SET rut_propietario = '7532446-4', nombre_propietario = 'ALFONSO LINCOYAN SALDAÑA FLORES', direccion_propietario = 'VILLA CENTINELA LUIS AMESTI 1478 SAN FERNANDO', telefono_propietario = '995489971', email_propietario = NULL, codigo_linea = '725', contrato_servicio = NULL WHERE patente = 'KYGL-92';
UPDATE flota.Vehiculo SET rut_propietario = '12414291-1', nombre_propietario = 'JOSE MIGUEL MARIQUEO DIAZ', direccion_propietario = 'VILLA DON DARIO PASAJE LOS NOGALES N° 081 SAN FERNANDO', telefono_propietario = '959890573', email_propietario = NULL, codigo_linea = '682', contrato_servicio = '14/06/2021' WHERE patente = 'KYGP-15';
UPDATE flota.Vehiculo SET rut_propietario = '18228886-1', nombre_propietario = 'GUSTAVO LOPEZ', direccion_propietario = 'CALLE DOC. MARIA AMPARO ARCAYAGA 58 V. MANSO DE VELASCO III', telefono_propietario = '975913553', email_propietario = NULL, codigo_linea = '705', contrato_servicio = '23-01-2025' WHERE patente = 'KYGP-18';
UPDATE flota.Vehiculo SET rut_propietario = '6395039-4', nombre_propietario = 'JOSE DAVID SILVA PEÑALOZA', direccion_propietario = 'POBL. LAUTARO PJE 7 N° 414 SAN FERNANDO', telefono_propietario = '978780705', email_propietario = NULL, codigo_linea = '663', contrato_servicio = NULL WHERE patente = 'KYGP-24';
UPDATE flota.Vehiculo SET rut_propietario = '13304298-9', nombre_propietario = 'CLAUDIO SERGIO CACERES MONTERO', direccion_propietario = 'LOS PALACIOS N° 955 SAN FERNANDO', telefono_propietario = '963947251', email_propietario = NULL, codigo_linea = '670', contrato_servicio = NULL WHERE patente = 'KYGP-27';
UPDATE flota.Vehiculo SET rut_propietario = '11743655-1', nombre_propietario = 'ANGEL RAMON ALVEAR CABEZAS', direccion_propietario = 'AV. JULIO FERNANDEZS/N AGUA BUENA SAN FERNANDO', telefono_propietario = '957694364', email_propietario = NULL, codigo_linea = '731', contrato_servicio = NULL WHERE patente = 'KYJF-68';
UPDATE flota.Vehiculo SET rut_propietario = '15118232-1', nombre_propietario = 'CRISTIAN CANALES MARAMBIO', direccion_propietario = 'MATEO Y TORO Y ZAMBRANO, SAN FERNANDO', telefono_propietario = '979996369', email_propietario = NULL, codigo_linea = '669', contrato_servicio = NULL WHERE patente = 'KYJT-10';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'PARCELA 4 MANZANA D MIRAVALLES', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '655', contrato_servicio = NULL WHERE patente = 'KYJT-17';
UPDATE flota.Vehiculo SET rut_propietario = '15119406-0', nombre_propietario = 'FERNANDO ANDRES ESPINOZA SEPULVEDA', direccion_propietario = 'CORONEL ERIC RIVEROS VALDES VILLA LOS REGIDORES SAN FERNANDO', telefono_propietario = '994467741', email_propietario = NULL, codigo_linea = '620', contrato_servicio = NULL WHERE patente = 'KZTY-67';
UPDATE flota.Vehiculo SET rut_propietario = '6646356-7', nombre_propietario = 'LUIS EDUARDO SILVA SILVA', direccion_propietario = 'POBLACION SAN HERNAN BLOCK 75 DPTO 32', telefono_propietario = '962625244', email_propietario = NULL, codigo_linea = '649', contrato_servicio = NULL WHERE patente = 'LSFL-43';
UPDATE flota.Vehiculo SET rut_propietario = '11743655-1', nombre_propietario = 'ANGEL RAMON ALVEAR CABEZAS', direccion_propietario = 'AV. JULIO FERNANDEZ  S/N AGUA BUENA SAN FERNANDO', telefono_propietario = '995769364', email_propietario = NULL, codigo_linea = '728', contrato_servicio = NULL WHERE patente = 'LZSR-61';
UPDATE flota.Vehiculo SET rut_propietario = '13304298-9', nombre_propietario = 'CLAUDIO CACERES M', direccion_propietario = 'VILLA VENECIA PSJE GRAL DE DIVISION JOAQUIN PRIETO N° 397', telefono_propietario = '963947251', email_propietario = NULL, codigo_linea = '606', contrato_servicio = NULL WHERE patente = 'LZSR-64';
UPDATE flota.Vehiculo SET rut_propietario = '9057615-1', nombre_propietario = 'HUGO ENRIQUE MUÑOZ SALINAS', direccion_propietario = 'VILLA DON DARIO PJE LOS PERALES N° 025 SAN FERNANDO', telefono_propietario = '949949218', email_propietario = NULL, codigo_linea = '610', contrato_servicio = '3/8/22' WHERE patente = 'LZSR-76';
UPDATE flota.Vehiculo SET rut_propietario = '8063610-5', nombre_propietario = 'NELSON MANUEL CASTILLO MOLINA', direccion_propietario = 'CONDOMINIO VILLA DON DARIO PSJE LOS NISPEROS 0136', telefono_propietario = '963868794', email_propietario = NULL, codigo_linea = '654', contrato_servicio = NULL WHERE patente = 'LZSR-99';
UPDATE flota.Vehiculo SET rut_propietario = '9276715-9', nombre_propietario = 'JORGE LUIS DIAZ VALENCIA', direccion_propietario = 'FRANCISCO DE LA LASTRA N° 1694 SAN FERNANDO', telefono_propietario = '993326487', email_propietario = NULL, codigo_linea = '676', contrato_servicio = NULL WHERE patente = 'LZSS-10';
UPDATE flota.Vehiculo SET rut_propietario = '16165484-1', nombre_propietario = 'NATALY FERNANDA PAVEZ GONZALEZ', direccion_propietario = 'MIRAFLORES 1480  CHIMBARONGO', telefono_propietario = '974898084', email_propietario = NULL, codigo_linea = '607', contrato_servicio = '23/09/2021' WHERE patente = 'LZSS-11';
UPDATE flota.Vehiculo SET rut_propietario = '10375863-7', nombre_propietario = 'JUAN ENRIQUE BECERRA BAEZA', direccion_propietario = 'VILLA SAN MARCO PSJE SANTO TOMAS 0470 SAN FERNANDO', telefono_propietario = '940631034', email_propietario = 'juanbecerra@gmail.com', codigo_linea = '634', contrato_servicio = NULL WHERE patente = 'LZSS-16';
UPDATE flota.Vehiculo SET rut_propietario = '11279329-1', nombre_propietario = 'CLAUDIO ENRIQUE TOLEDO LALANNE', direccion_propietario = 'CAMINO LAS QUEZADAS CASA 26 TINGUIRIRICA , CHIMBARONGO', telefono_propietario = '974520144', email_propietario = NULL, codigo_linea = '626', contrato_servicio = NULL WHERE patente = 'LZSS-24';
UPDATE flota.Vehiculo SET rut_propietario = '9136775-0', nombre_propietario = 'ALIRO HUMBERTO ROJAS FUENTES', direccion_propietario = 'POBLACION SAN HERNAN BLOCK 59 DPTO 12 SAN FERNANDO', telefono_propietario = '992324152', email_propietario = NULL, codigo_linea = '613', contrato_servicio = '1/12/22' WHERE patente = 'LZSS-30';
UPDATE flota.Vehiculo SET rut_propietario = '16973070-9', nombre_propietario = 'FRANCISCO JAVIER OLGUIN SILVA', direccion_propietario = 'VILLA GALILEA CALLE PROFESOR ABRAHAM SILVA  TRIVIÑO 019 SAN FERNANDO', telefono_propietario = '930824204', email_propietario = NULL, codigo_linea = '691', contrato_servicio = NULL WHERE patente = 'LZTR-17';
UPDATE flota.Vehiculo SET rut_propietario = '11530199-3', nombre_propietario = 'MARIO ALBERTO ZUÑIGA GONZALEZ', direccion_propietario = 'ALCAYAGA N° 1025 GABRIELA MISTRAL SAN FERNANDO', telefono_propietario = '985378365', email_propietario = NULL, codigo_linea = '636', contrato_servicio = NULL WHERE patente = 'LZTR-41';
UPDATE flota.Vehiculo SET rut_propietario = '15915952-3', nombre_propietario = 'JOSE RODRIGO CANTILLANA BURGOS', direccion_propietario = 'NINCUNLAUTA N° 216 SAN FERNANDO', telefono_propietario = '992052298', email_propietario = NULL, codigo_linea = '667', contrato_servicio = NULL WHERE patente = 'LZTZ-16';
UPDATE flota.Vehiculo SET rut_propietario = '7903010-4', nombre_propietario = 'NEMESIA AUDOMIRA ORELLANA MARTINEZ', direccion_propietario = 'LA LAJUELA 0256 JARDINES RUCATALCA, SAN FERNANDO', telefono_propietario = '941704209', email_propietario = NULL, codigo_linea = '632', contrato_servicio = NULL WHERE patente = 'LZTZ-47';
UPDATE flota.Vehiculo SET rut_propietario = '6686710-2', nombre_propietario = 'NELSON ORLANDO BOZO BECERRA', direccion_propietario = 'PASAJE 2, 1331 POBLACION LAUTARO SAN FERNANDO', telefono_propietario = '999579931', email_propietario = NULL, codigo_linea = '621', contrato_servicio = NULL WHERE patente = 'LZTZ-49';
UPDATE flota.Vehiculo SET rut_propietario = '18558878-5', nombre_propietario = 'ANGEL ANDRÉS ALVEAR ROJAS', direccion_propietario = 'AV. JULIO FERNANDEZ S/N AGUA BUENA SAN FERNANDO', telefono_propietario = '932077610', email_propietario = NULL, codigo_linea = '714', contrato_servicio = NULL WHERE patente = 'LZVK-65';
UPDATE flota.Vehiculo SET rut_propietario = '130042414', nombre_propietario = 'ROBERTO ANTONIO GONZALEZ HERRERA', direccion_propietario = 'CALLEJON LOS NARANJOS S/N ROMA SAN FERNANDO', telefono_propietario = '990357115', email_propietario = NULL, codigo_linea = '642', contrato_servicio = NULL WHERE patente = 'LZVK-66';
UPDATE flota.Vehiculo SET rut_propietario = '10863146-5', nombre_propietario = 'JUAN RIGOBERTO ZAMORANO VASQUEZ', direccion_propietario = 'VILLA GABRIELA MISTRAL, PSJE VICUÑA N° 1097 SAN FERNANDO', telefono_propietario = '982527488', email_propietario = NULL, codigo_linea = '628', contrato_servicio = NULL WHERE patente = 'LZVK-70';
UPDATE flota.Vehiculo SET rut_propietario = '11952501-2', nombre_propietario = 'ANDRES SEGUNDO SANHUEZA PADILLA', direccion_propietario = 'VILLA EL ALAMO, PASAJE GUILLERMO MARKMAN 543 SAN FERNANDO', telefono_propietario = '961658380', email_propietario = NULL, codigo_linea = '623', contrato_servicio = NULL WHERE patente = 'LZVK-71';
UPDATE flota.Vehiculo SET rut_propietario = '8982188-6', nombre_propietario = 'CARLOS ALEX QUEZADA SALINAS', direccion_propietario = 'VILLA PRINCIPAL PSJE CARLOS BRITO 0385', telefono_propietario = '958912317', email_propietario = NULL, codigo_linea = '640', contrato_servicio = NULL WHERE patente = 'LZVK-79';
UPDATE flota.Vehiculo SET rut_propietario = '8163423-8', nombre_propietario = 'MARISOL MONICA ARANDA AUSENSI', direccion_propietario = 'VILLA EDUARDO BARRIO PASAJE 2  N° 1656 SAN FERNANDO', telefono_propietario = '981646526', email_propietario = NULL, codigo_linea = '699', contrato_servicio = NULL WHERE patente = 'LZVK-89';
UPDATE flota.Vehiculo SET rut_propietario = '6759634-K', nombre_propietario = 'RUBEN OCTAVIO JARA LOBOS', direccion_propietario = 'RIVERA DEL RIO N° 38 POBLACION SANTA ELENA SAN FERNANDO', telefono_propietario = '995059577', email_propietario = NULL, codigo_linea = '637', contrato_servicio = NULL WHERE patente = 'LZVK-96';
UPDATE flota.Vehiculo SET rut_propietario = '17133992-8', nombre_propietario = 'GONZALO ANDRES ZUÑIGA ACEVEDO', direccion_propietario = 'CONDOMINIO ALTO LA PALTA, TORRE A, DPTO 503 SAN FERNANDO', telefono_propietario = '958766957', email_propietario = NULL, codigo_linea = '633', contrato_servicio = NULL WHERE patente = 'LZWH-40';
UPDATE flota.Vehiculo SET rut_propietario = '10303667-4', nombre_propietario = 'JUAN CARLOS BRIONES GUAJRDO', direccion_propietario = 'MATEO DE TORO Y ZAMBRANO N° 1422 POBL. 18 SEPTIEMBRE SAN FERNANDO', telefono_propietario = '984503298', email_propietario = NULL, codigo_linea = '675', contrato_servicio = NULL WHERE patente = 'LZWX-73';
UPDATE flota.Vehiculo SET rut_propietario = '15117148-6', nombre_propietario = 'ALEXI ANDRÉS COFRÉ VALENZUELA', direccion_propietario = 'VILLA LOS REGIDORES, PSJE HERNAN MARTINO N° 829 SAN FERNANDO', telefono_propietario = '945107090', email_propietario = NULL, codigo_linea = '673', contrato_servicio = NULL WHERE patente = 'LZWX-87';
UPDATE flota.Vehiculo SET rut_propietario = '13437650-4', nombre_propietario = 'CRISTIAN ANDRES MENESES ESPINOZA', direccion_propietario = 'LAS ROSAS SITIO 2 SAN FERNANDO', telefono_propietario = '972954597', email_propietario = NULL, codigo_linea = '624', contrato_servicio = NULL WHERE patente = 'LZWY-41';
UPDATE flota.Vehiculo SET rut_propietario = '9145768-7', nombre_propietario = 'JOSE ATILIO CANTILLANA ORELLANA', direccion_propietario = 'ANGEL CRUCHAGA N° 532 VILLA LOS ARREGLADORES SAN FERNANDO', telefono_propietario = '957557404', email_propietario = NULL, codigo_linea = '719', contrato_servicio = NULL WHERE patente = 'PLHW-88';
UPDATE flota.Vehiculo SET rut_propietario = '15117610-0', nombre_propietario = 'JUAN LUIS MORALES PAVEZ', direccion_propietario = 'CORONEL EROCK RIVEROS VALDES  819 V. LOS REGIDORES  SN FDO.', telefono_propietario = '920255153', email_propietario = NULL, codigo_linea = '662', contrato_servicio = '26/03/2025' WHERE patente = 'PLRC-77';
UPDATE flota.Vehiculo SET rut_propietario = '8045345-0', nombre_propietario = 'JOSE RICHARD ALARCON MATUS', direccion_propietario = 'PJE VICUÑA N° 1050 SAN FERNANDO', telefono_propietario = '932692449', email_propietario = NULL, codigo_linea = '674', contrato_servicio = NULL WHERE patente = 'PVSR-16';
UPDATE flota.Vehiculo SET rut_propietario = '8874151-K', nombre_propietario = 'MIGUEL ANGEL ESPINA GAETE', direccion_propietario = 'PJE GALVARINO153 NANCAGUA', telefono_propietario = '990194559', email_propietario = NULL, codigo_linea = '692', contrato_servicio = NULL WHERE patente = 'PSDH-31';
UPDATE flota.Vehiculo SET rut_propietario = '9111630-8', nombre_propietario = 'PATRICIA BERNARDITA QUEZADA MENESES', direccion_propietario = 'LORENZO OYANGURE N°0356 VILLA DOÑA ESTER 4 SAN FERNANDO', telefono_propietario = '932834715', email_propietario = NULL, codigo_linea = '672', contrato_servicio = NULL WHERE patente = 'PVPH-73';
UPDATE flota.Vehiculo SET rut_propietario = '13347885-K', nombre_propietario = 'CRISTIAN ALBERTO POZO VILLEGAS', direccion_propietario = 'POBLACIÓN ALBORADA CALLE RIVERA DEL RIO S/N°', telefono_propietario = '989305138', email_propietario = NULL, codigo_linea = '686', contrato_servicio = NULL WHERE patente = 'PVPH-92';
UPDATE flota.Vehiculo SET rut_propietario = '13779833-6', nombre_propietario = 'CESAR ANTONIO BARRA BECERRA', direccion_propietario = 'PARCELA 17 SITIO 7 SAN ANTONIO CHIMBARONGO', telefono_propietario = '932607337', email_propietario = NULL, codigo_linea = '664', contrato_servicio = NULL WHERE patente = 'PVPH-99';
UPDATE flota.Vehiculo SET rut_propietario = '9503594-9', nombre_propietario = 'JUAN CARLOS JOVE SILVA', direccion_propietario = 'IGNACIO LO CARRERA N° 8386 SAN FERNANDO', telefono_propietario = '958037150', email_propietario = NULL, codigo_linea = '677', contrato_servicio = NULL WHERE patente = 'PVPJ-19';
UPDATE flota.Vehiculo SET rut_propietario = '15528046-8', nombre_propietario = 'ANDRES ALEJANDRO JORQUERA MORENO', direccion_propietario = 'AVENIDA PORTALES 4040 SANTIAGO', telefono_propietario = '986100865', email_propietario = 'jmoreno.ajm@gmail.com', codigo_linea = '618', contrato_servicio = NULL WHERE patente = 'PVPR-12';
UPDATE flota.Vehiculo SET rut_propietario = '11530199-3', nombre_propietario = 'MARIO ALBERTO ZUÑIGA GONZALEZ', direccion_propietario = 'ALCAYAGA 1025 VILLA GABRIELA MISTRAL SAN FERNANDO', telefono_propietario = '985378365', email_propietario = NULL, codigo_linea = '646', contrato_servicio = NULL WHERE patente = 'PVPR-16';
UPDATE flota.Vehiculo SET rut_propietario = '8981855-9', nombre_propietario = 'LUIS TRUJILLO SANTIBAÑEZ', direccion_propietario = 'PORVENIR NORTE SANTA BERNARDITA 33', telefono_propietario = '999201581', email_propietario = 'luistrujillo@gmai.com', codigo_linea = '602', contrato_servicio = NULL WHERE patente = 'PVPR-33';
UPDATE flota.Vehiculo SET rut_propietario = '7671818-0', nombre_propietario = 'JOSE MANUEL MUÑOZ VALENZUELA', direccion_propietario = 'VILLA EL ALAMO CAPITAN LUIS DE VELASCO N° 561', telefono_propietario = '982338183', email_propietario = NULL, codigo_linea = '617', contrato_servicio = NULL WHERE patente = 'PVRC-66';
UPDATE flota.Vehiculo SET rut_propietario = '10697849-2', nombre_propietario = 'MARIO REBOLLEDO WACEOLS', direccion_propietario = 'POBL. 18 DE SEPTIEMBRE  RIO RIGOLEMU 1713', telefono_propietario = '949368325', email_propietario = NULL, codigo_linea = '734', contrato_servicio = NULL WHERE patente = 'PVRC-68';
UPDATE flota.Vehiculo SET rut_propietario = '15698523-6', nombre_propietario = 'LUIS TORRES HUERTA', direccion_propietario = 'VILLA PRINCIPAL PSJE SA JOSE MORALES 1336', telefono_propietario = '978879433', email_propietario = NULL, codigo_linea = '601', contrato_servicio = 'C:\Servitaco\Servicios\Servicio-CZYR-54.pdf' WHERE patente = 'PVRC-71';
UPDATE flota.Vehiculo SET rut_propietario = '6017825-9', nombre_propietario = 'LUIS ORLANDO RIQUELME MATURANA', direccion_propietario = 'PARCELA 4 MANZANA D MIRAVALLES LOS LINGUES', telefono_propietario = '994426413', email_propietario = NULL, codigo_linea = '629', contrato_servicio = NULL WHERE patente = 'PVRC-99';
UPDATE flota.Vehiculo SET rut_propietario = '9040174-2', nombre_propietario = 'LUIS ESPINOZA DIAZ', direccion_propietario = 'VILLA PRINCIPAL PASAJE JUAN JOSE DE MORALES 1337', telefono_propietario = '997572632', email_propietario = NULL, codigo_linea = '703', contrato_servicio = NULL WHERE patente = 'PVRH-71';
UPDATE flota.Vehiculo SET rut_propietario = '7354610-9', nombre_propietario = 'ANGEL GALARCE GALARCE', direccion_propietario = 'RINCONADA DE MANANTIALES PLACILLA', telefono_propietario = '934329700', email_propietario = NULL, codigo_linea = '652', contrato_servicio = NULL WHERE patente = 'PVSD-89';
UPDATE flota.Vehiculo SET rut_propietario = '12780992-5', nombre_propietario = 'MARIO DIAZ ORTIZ', direccion_propietario = 'VILLA LOS PARRONES CALLE6 CASA 5 LA LUCANA', telefono_propietario = '982796190', email_propietario = 'MARIOFERNANDODIAZORTIZ@GMAIL.COM', codigo_linea = '732', contrato_servicio = NULL WHERE patente = 'PVSH-12';
UPDATE flota.Vehiculo SET rut_propietario = '5246025-5', nombre_propietario = 'SERGIO DEL CARMEN SALAZAR RETAMALES', direccion_propietario = 'MONTENEGRO N° 07 TINGUIRIRICA CHIMBARONGO', telefono_propietario = '996281232', email_propietario = NULL, codigo_linea = '688', contrato_servicio = NULL WHERE patente = 'RGCT-29';
UPDATE flota.Vehiculo SET rut_propietario = '15698238-5', nombre_propietario = 'PATRICIO FERNANDO LABRAÑA MURILLO', direccion_propietario = 'CALLE FRANCISCO DE AGUIRRE 090 SAN FERNANDO', telefono_propietario = '995297504', email_propietario = NULL, codigo_linea = '619', contrato_servicio = NULL WHERE patente = 'SRXK-67';
UPDATE flota.Vehiculo SET rut_propietario = '5246025-5', nombre_propietario = 'SERGIO DEL CARMEN SALAZAR MENESES', direccion_propietario = 'MONTE NEGRO 07 CHIMBARONGO', telefono_propietario = '995382380', email_propietario = NULL, codigo_linea = '709', contrato_servicio = NULL WHERE patente = 'TFRP-45';
UPDATE flota.Vehiculo SET rut_propietario = '5246025-5', nombre_propietario = 'SERGIO DEL CARMEN SALAZAR RETAMALES', direccion_propietario = 'MONTE NEGRO', telefono_propietario = '996281232', email_propietario = NULL, codigo_linea = '718', contrato_servicio = NULL WHERE patente = 'THSG-68';
UPDATE flota.Vehiculo SET rut_propietario = '13201862-6', nombre_propietario = 'PEDRO EMILIO ABARCA PAVEZ', direccion_propietario = 'ALCIDES ROLDAN N° 1459 SAN FERNANDO', telefono_propietario = '963720439', email_propietario = NULL, codigo_linea = '678', contrato_servicio = NULL WHERE patente = 'TKHB-59';
UPDATE flota.Vehiculo SET rut_propietario = '16165038-2', nombre_propietario = 'VICTOR MOSCOSO P', direccion_propietario = 'PSJE ANGEL CRUCHAGA V. LOS ARREGLADORES SAN FERNANDO', telefono_propietario = '974282163', email_propietario = NULL, codigo_linea = '697', contrato_servicio = NULL WHERE patente = 'VHDP-18';
UPDATE flota.Vehiculo SET rut_propietario = '14260593-7', nombre_propietario = 'MANUEL VIDELA CHAVEZ', direccion_propietario = 'ROMA LO CARREÑO S/N', telefono_propietario = '947480094', email_propietario = NULL, codigo_linea = '737', contrato_servicio = '29/09/2025' WHERE patente = 'VHDR-86';
UPDATE flota.Vehiculo SET rut_propietario = '13201285-7', nombre_propietario = 'PAULINA LORETO TOBAR ROSEL', direccion_propietario = 'NINCUNLAUTA N° 43 SAN FERNANDO', telefono_propietario = '991969783', email_propietario = NULL, codigo_linea = '689', contrato_servicio = NULL WHERE patente = 'HTWP-66';
GO
